defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 30
        hidden: false
pager:
  diff: delta

theme:
  ui:
    table:
      showSeparator: true
  colors:
    text:
      primary: "#f8f8f2"
      secondary: "#ffb86c"
      inverted: "#282a36"
      faint: "#797d9c"
      warning: "#ff5555"
      success: "#50fa7b"
    background:
      selected: "#292e42"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
